import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    loadingPage: true,
    isFullScreen: false,
    fullScreenImages: [],
    isDesktopView: window.innerWidth >= 900,
    layoutGrid: "",
    singlePortfolioPage: true,
    isLeftMenuActive: false,
    isRightMenuActive: false,
    isRightMenuNotActive: true,
    isSubItems: false,
    isSubItem: false,
    isOnePage: false,
    xSlideIndex: 0,
    xPosition: 0,
    projects: [
      {
        title: "Arter",
        images: [],
        description: "",
        orderDate: "",
        finalDate: "",
        status: "",
        client: "",
        location: "",
      },
    ],
    filterLinks: [
      // {
      //   content: "All Categories",
      //   dataFilter: "*",
      // },
      // {
      //   content: "Web Templates",
      //   dataFilter: ".webTemplates",
      // },
      // {
      //   content: "Logos",
      //   dataFilter: ".logos",
      // },
      // {
      //   content: "Drawings",
      //   dataFilter: ".drawings",
      // },
      // {
      //   content: "UI Elements",
      //   dataFilter: ".ui",
      // },
    ],
    detailedProject: {
      header: {
        title: "Arter",
        content: "Web Development",
      },
      card: {
        title: "Description",
        content: "Content",
        buttonContent: "Go to Website",
        href: "https://www.arter.bektasalbayrak.com",
      },
      tableList: [
        {
          key: "Order Date:",
          value: "24.12.2019",
        },
        {
          key: "Final Date:",
          value: "12.03.2020",
        },
        {
          key: "Status",
          value: "Completed",
        },
        {
          key: "Client",
          value: "Envato Market",
        },
        {
          key: "Location",
          value: "Ukraine, Lviv",
        },
      ],
      images: [
        {
          imageSrc: require("../assets/img/single/1.jpeg"),
          imageAlt: "",
          isBlog: true,
          isSlide: true,
        },
        {
          imageSrc: require("../assets/img/single/7.jpeg"),
          imageAlt: "",
          isBlog: true,
          isSlide: true,
        },
        {
          imageSrc: require("../assets/img/single/4.jpeg"),
          imageAlt: "",
          isBlog: true,
          isSlide: true,
        },
        {
          imageSrc: require("../assets/img/single/5.jpeg"),
          imageAlt: "",
          isBlog: true,
          isSlide: true,
        },
        {
          imageSrc: require("../assets/img/single/4.jpeg"),
          imageAlt: "",
          isBlog: true,
          isSlide: true,
        },
      ],
      imageSrc: require("../assets/img/bektasalbayrak.jpg"),
      imageAlt: "portfolio 1",
      imagehref: "/project/arter",
      content: "Clone from Arter Design",
      href: "/project/arter",
      size: "short",
      dataFilter: ".webTemplates",
      buttonContent: "Read more",
    },
    showingPortfolioCards: [],
    portfolioCards: [
      {
        header: {
          title: "Arter",
          content: "Web Development",
        },
        card: {
          title: "Description",
          content: "Content",
          buttonContent: "Go to Website",
          outOfProject: true,
          isBlank: true,
          href: "https://arter.bektasalbayrak.com",
        },
        tableList: [
          {
            key: "Order Date:",
            value: "24.12.2019",
          },
          {
            key: "Final Date:",
            value: "12.03.2020",
          },
          {
            key: "Status",
            value: "Completed",
          },
          {
            key: "Client",
            value: "Envato Market",
          },
          {
            key: "Location",
            value: "Ukraine, Lviv",
          },
        ],
        images: [
          {
            imageSrc: require("../assets/arter-design/home.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/arter-design/home-2.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/arter-design/portfolio.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/arter-design/blog.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/arter-design/result.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
        ],
        imageSrc: require("../assets/arter-design/home.png"),
        imageAlt: "portfolio 1",
        imagehref: "/project/arter",
        content: "Clone from Arter Design",
        href: "/project/arter",
        size: "short",
        dataFilter: ".webTemplates",
        buttonContent: "Reads more",
        title: "Arter",
        id: "arter",
      },
      {
        header: {
          title: "Cv-maker",
          content: "Web Development",
        },
        card: {
          title: "Description",
          content: "Cv-maker content",
          buttonContent: "Go to Website",
          outOfProject: true,
          isBlank: true,
          href: "https://cv-maker.bektasalbayrak.com",
        },
        tableList: [
          {
            key: "Order Date:",
            value: "24.12.2222",
          },
          {
            key: "Final Date:",
            value: "12.03.2222",
          },
          {
            key: "Status",
            value: "Completed",
          },
          {
            key: "Client",
            value: "Envato 2222",
          },
          {
            key: "Location",
            value: "Ukraine, 2222",
          },
        ],
        images: [
          {
            imageSrc: require("../assets/cv-maker/home.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/cv-maker/home-2.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/cv-maker/color.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/cv-maker/font.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/cv-maker/empty-cv.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
        ],
        imageSrc: require("../assets/cv-maker/home.png"),
        imageAlt: "portfolio 1",
        imagehref: "cv-maker",
        content: "Website for make resume",
        href: "/project/cv-maker",
        size: "short",
        dataFilter: ".webTemplates",
        buttonContent: "Read more",
        title: "Cv-maker",
        id: "cv-maker",
      },
      {
        header: {
          title: "Ramsey",
          content: "Web Development",
        },
        card: {
          title: "Description",
          content: "Ramsey Design content",
          buttonContent: "Go to Website",
          outOfProject: true,
          isBlank: true,
          href: "https://ramsey.bektasalbayrak.com",
        },
        tableList: [
          {
            key: "Order Date:",
            value: "24.12.2222",
          },
          {
            key: "Final Date:",
            value: "12.03.2222",
          },
          {
            key: "Status",
            value: "Completed",
          },
          {
            key: "Client",
            value: "Envato 2222",
          },
          {
            key: "Location",
            value: "Ukraine, 2222",
          },
        ],
        images: [
          {
            imageSrc: require("../assets/ramsey-design/home.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/ramsey-design/about.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/ramsey-design/contact.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/ramsey-design/menu.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/ramsey-design/specialization.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
        ],
        imageSrc: require("../assets/ramsey-design/home.png"),
        imageAlt: "portfolio 1",
        imagehref: "ramsey",
        content: "Clone from Ramsey Design",
        href: "/project/ramsey",
        size: "short",
        dataFilter: ".webTemplates",
        buttonContent: "Read more",
        title: "Ramsey",
        id: "ramsey",
      },
      {
        header: {
          title: "Photographer",
          content: "Web Development",
        },
        card: {
          title: "Description",
          content: "photographer content",
          buttonContent: "Go to Website",
          outOfProject: true,
          isBlank: true,
          href: "https://photographer.bektasalbayrak.com",
        },
        tableList: [
          {
            key: "Order Date:",
            value: "24.12.2222",
          },
          {
            key: "Final Date:",
            value: "12.03.2222",
          },
          {
            key: "Status",
            value: "Completed",
          },
          {
            key: "Client",
            value: "Envato 2222",
          },
          {
            key: "Location",
            value: "Ukraine, 2222",
          },
        ],
        images: [
          {
            imageSrc: require("../assets/photopgrapher/home.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/photopgrapher/home-2.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/photopgrapher/full-screen.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/photopgrapher/albums.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/photopgrapher/home.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
        ],
        imageSrc: require("../assets/photopgrapher/home.png"),
        imageAlt: "portfolio 1",
        imagehref: "photographer",
        content: "Photographer Design",
        href: "/project/photographer",
        size: "short",
        dataFilter: ".webTemplates",
        buttonContent: "Read more",
        title: "Photographer",
        id: "photographer",
      },
      {
        header: {
          title: "Todo App",
          content: "Web Development",
        },
        card: {
          title: "Description",
          content: "todo content",
          buttonContent: "Go to Website",
          outOfProject: true,
          isBlank: true,
          href: "https://todo.bektasalbayrak.com",
        },
        tableList: [
          {
            key: "Order Date:",
            value: "24.12.2222",
          },
          {
            key: "Final Date:",
            value: "12.03.2222",
          },
          {
            key: "Status",
            value: "Completed",
          },
          {
            key: "Client",
            value: "Envato 2222",
          },
          {
            key: "Location",
            value: "Ukraine, 2222",
          },
        ],
        images: [
          {
            imageSrc: require("../assets/todo/home.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/todo/home-2.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/todo/new-task.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/todo/menu.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
          {
            imageSrc: require("../assets/todo/home-mobile.png"),
            imageAlt: "",
            isBlog: true,
            isSlide: true,
          },
        ],
        imageSrc: require("../assets/todo/home.png"),
        imageAlt: "portfolio 1",
        imagehref: "todo",
        content: "Todo Web App",
        href: "/project/todo",
        size: "short",
        dataFilter: ".webTemplates",
        buttonContent: "Read more",
        title: "Todo",
        id: "todo",
      },
    ],
    blogCardList: [
      {
        imageSrc: require("../assets/img/blog/1.jpeg"),
        imageAlt: "blog image",
        imagehref: "singleproject",
        title: "Blog post title",
        content: "Sit amet, consectetur adipisicing elit. Quas, architecto.",
        href: "singleproject",
        buttonContent: "Read more",
        isBlog: true,
      },
      {
        imageSrc: require("../assets/img/blog/2.jpeg"),
        imageAlt: "blog image",
        imagehref: "singleproject",
        title: "Blog post title",
        content: "Sit amet, consectetur adipisicing elit. Quas, architecto.",
        href: "singleproject",
        buttonContent: "Read more",
        isBlog: true,
      },
      {
        imageSrc: require("../assets/img/blog/3.jpeg"),
        imageAlt: "blog image",
        imagehref: "singleproject",
        title: "Blog post title",
        content: "Sit amet, consectetur adipisicing elit. Quas, architecto.",
        href: "singleproject",
        buttonContent: "Read more",
        isBlog: true,
      },
      {
        imageSrc: require("../assets/img/blog/4.jpeg"),
        imageAlt: "blog image",
        imagehref: "singleproject",
        title: "Blog post title",
        content: "Sit amet, consectetur adipisicing elit. Quas, architecto.",
        href: "singleproject",
        buttonContent: "Read more",
        isBlog: true,
      },
      {
        imageSrc: require("../assets/img/blog/5.jpeg"),
        imageAlt: "blog image",
        imagehref: "singleproject",
        title: "Blog post title",
        content: "Sit amet, consectetur adipisicing elit. Quas, architecto.",
        href: "singleproject",
        buttonContent: "Read more",
        isBlog: true,
      },
      {
        imageSrc: require("../assets/img/blog/6.jpeg"),
        imageAlt: "blog image",
        imagehref: "singleproject",
        title: "Blog post title",
        content: "Sit amet, consectetur adipisicing elit. Quas, architecto.",
        href: "singleproject",
        buttonContent: "Read more",
        isBlog: true,
      },
      {
        imageSrc: require("../assets/img/blog/7.jpeg"),
        imageAlt: "blog image",
        imagehref: "singleproject",
        title: "Blog post title",
        content: "Sit amet, consectetur adipisicing elit. Quas, architecto.",
        href: "singleproject",
        buttonContent: "Read more",
        isBlog: true,
      },
      {
        imageSrc: require("../assets/img/blog/8.jpeg"),
        imageAlt: "blog image",
        imagehref: "singleproject",
        title: "Blog post title",
        content: "Sit amet, consectetur adipisicing elit. Quas, architecto.",
        href: "singleproject",
        buttonContent: "Read more",
        isBlog: true,
      },
    ],
  },
  getters: {
    getFullScreenImages(state) {
      return state.fullScreenImages;
    },
  },
  mutations: {},
  actions: {},
  modules: {},
});
